name:  Continuous Deployment

on:
  push:
    branches:
      - 'main'
      - 'develop'    
      - 'release/**'    

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Retrieve the certificate
      run: |
        echo $CERTIFICATE_BASE64 | base64 -d > ioc-dot-net.snk
      shell: bash
      env:
        CERTIFICATE_BASE64: ${{secrets.CERTIFICATE_BASE64}}


    - name: Build
      env:
        Configuration: 'Release'
      run: |
        dotnet build  -v:m 


    # - name: Label Fixed Issues
    #   uses: gh-bot/fix-labeler@master        


