name:  Continuous Deployment

on:
  push:
    branches:
      - 'main'
      - 'develop'    
      - 'release/**'    

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    # - name: Restore
    #   run: dotnet restore

    - name: Build
      env:
        Configuration: 'Release'
      run: |
        dotnet build  -v:m 


    - name: Retrieve the certificate
      env:
        CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
      run: |
        echo $CERTIFICATE_BASE64 | base64 --decode > ioc-dot-net.snk

    - name: Show certificate information
      run: |
        openssl x509 -in ioc-dot-net.snk -inform snk -text -noout

    - name: Label Fixed Issues
      uses: gh-bot/fix-labeler@master        
